@startuml

' 描画すべきエレメントタイプ
!function $get_describing_element_()
    !return $iumlLib_display_level
!endfunction

' メッセージの送り元オブジェクト
!function $get_from_object_()
    !return $get_object_( $get_value_in_current_stack( "func" ) )
!endfunction

' メッセージの送り先オブジェクト
!function $get_to_object_( $to="return" )
    !if $to == "return"
        !return $get_object_( $get_value_in_prev_stack( "func" ) )
    !else
        !return $get_object_( $to )
    !endif
!endfunction

' 実行中のオブジェクト
!function $get_current_object_()
    !return $get_object_( $get_value_in_current_stack( "func" ) )
!endfunction

' 関数名に紐づくオブジェクト
!function $get_object_( $func )
    !if $func == ""
        ' 関数名が空文字の場合はエントリポイント
        !$object = $sdlConf_entry_point
    !else
        !$element_type = $get_describing_element_()
        !$module       = %get_variable_value( $func + ".module" )
        !$component    = %get_variable_value( $module + ".component" )

        ' 描画対象のエレメントが関数 or 詳細に描画するモジュールとして指定されている or 詳細に描画するコンポ且つ粒度が関数で指定されている
        !if ( ( $element_type == "func" ) || ( $sdlConf_display_lifeline_focused_element == $module ) || ( ( $sdlConf_display_lifeline_focused_element == $component ) && ( $sdlConf_display_lifeline_focused_element_level == "func" ) ) )
            !$object = $func
        ' 描画対象のエレメントがモジュール or 詳細に描画するコンポーネントとして指定されている
        !elseif ( (  $element_type == "module" ) || ( $sdlConf_display_lifeline_focused_element == $component ) )
            !$object = $module
        !else
            !$object = $component
        !endif

        ' オブジェクトが見つからない場合
        !if $object == ""
            !if $element_type == "func"
                !$object = $func
            !else
                !$object = "External_" + $element_type
            !endif
        !endif
    !endif
    !return $object
!endfunction

' 利用されるオブジェクトタイプ
!function $get_object_type_( $func )
    !if $func == ""
        ' 関数名が空文字の場合はエントリポイント
        !$object_type = "func"
    !else
        !$element_type = $get_describing_element_()
        !$module       = %get_variable_value( $func + ".module" )
        !$component    = %get_variable_value( $module + ".component" )

        ' 描画対象のエレメントが関数 or 詳細に描画するモジュールとして指定されている or 詳細に描画するコンポ且つ粒度が関数で指定されている
        !if ( ( $element_type == "func" ) || ( $sdlConf_display_lifeline_focused_element == $module ) || ( ( $sdlConf_display_lifeline_focused_element == $component ) && ( $sdlConf_display_lifeline_focused_element_level == "func" ) ) )
            !$object_type = "func"
        ' 描画対象のエレメントがモジュール or 詳細に描画するコンポーネントとして指定されている
        !elseif ( (  $element_type == "module" ) || ( $sdlConf_display_lifeline_focused_element == $component ) )
            !$object_type = "module"
        !else
            !$object_type = "component"
        !endif
    !endif
    !return $object_type
!endfunction

@enduml
