@startuml
'#==============================================================================================
'# file : C:\workspace\c2puml\demo\example\test1.c
'#==============================================================================================
$start_component("example")
$start_module("test1.c")

'#----------------------------------------------------
'# func :  ## void ## EntryPoint ## ( void )
'#----------------------------------------------------
$start_func("EntryPoint", "extern")
!procedure $EntryPoint()
    $call("test2_globalCall")
    $call("localCall")
!endprocedure

'#----------------------------------------------------
'# func : static ## void ## localCall ## (void)
'#----------------------------------------------------
$start_func("localCall", "static")
!procedure $test1_c_____localCall()
    $step(" int i = 0;")
    $step(" i *= 2;")
!endprocedure


'#==============================================================================================
'# file : C:\workspace\c2puml\demo\example\test2.c
'#==============================================================================================
$start_component("example")
$start_module("test2.c")

'#----------------------------------------------------
'# func :  ## void ## test2_globalCall ## ( void )
'#----------------------------------------------------
$start_func("test2_globalCall", "extern")
!procedure $test2_globalCall()
    $call("localCall")
!endprocedure

'#----------------------------------------------------
'# func : static ## void ## localCall ## (void)
'#----------------------------------------------------
$start_func("localCall", "static")
!procedure $test2_c_____localCall()
    $step(" int x = 0;")
    $step(" x *= 2;")
!endprocedure


$box()
$call("EntryPoint")
@enduml

