@startuml
'#==============================================================================================
'# file : C:\workspace\c2puml\demo\example\system\core\lib\s_main.c
'#==============================================================================================
$start_component("system.core.lib")
$start_module("s_main.c")

'#----------------------------------------------------
'# func :  ## int WINAPI ## _tWinMain ## ( HINSTANCE a_hApp, HINSTANCE a_hAppPrev, LPSTR a_szCmdLine, int a_modCmdShow )
'#----------------------------------------------------
$start_func("_tWinMain", "extern")
!procedure $_tWinMain()
    $step(" a_modResult = 0;")
    $call("l_voSetCmdLine", " a_szCmdLine ")
    $call("l_voSetHndApp", " a_hApp ")
    $call("l_boolInitSystem", " a_hApp, a_modCmdShow ")
    $call("g_boolHookInitApp", "")
    $if("( TRUE == a_boolInitSystem ) && ( TRUE == a_boolHookInitApp ) ")
        $call("l_modMsgLoop", "")
        $call("g_voHookTermApp", "")
    $else()
    $endif()
    $return("a_modResult")
!endprocedure

'#----------------------------------------------------
'# func : static ## int ## l_modMsgLoop ## ( void )
'#----------------------------------------------------
$start_func("l_modMsgLoop", "static")
!procedure $s_main_c_____l_modMsgLoop()
    $step(" a_modResult = 0;")
    $step(" a_bMsg = TRUE;")
    $while("a_bMsg == TRUE ")
        $call("GetMessage", " &a_msg, NULL, 0, 0 ")
        $switch("message ")
        $case("L_MOD_GM_FAILURE")
            $step(" a_bMsg = FALSE;")
        $case("L_MOD_GM_WM_QUIT")
            $step(" a_bMsg = FALSE;")
            $step(" a_modResult = (int)a_msg.wParam;")
        $default()
            $step(" a_bMsg = TRUE;")
            $call("TranslateMessage", " &a_msg ")
            $call("DispatchMessage", " &a_msg ")
        $endswitch()
    $endwhile()
    $return("a_modResult")
!endprocedure

'#----------------------------------------------------
'# func : static ## BOOL ## l_boolInitSystem ## ( const HINSTANCE a_hApp, const int a_modCmdShow )
'#----------------------------------------------------
$start_func("l_boolInitSystem", "static")
!procedure $s_main_c_____l_boolInitSystem()
    $step(" a_bInitSystem = FALSE;")
    $call("g_atomRegisterWcex", " a_hApp ")
    $if("a_result != 0 ")
        $call("g_hwndCreateWindow", " a_hApp ")
        $if("a_hWnd != NULL ")
            $step(" a_bInitSystem = TRUE;")
            $call("ShowWindow", " a_hWnd, a_modCmdShow ")
            $call("UpdateWindow", " a_hWnd ")
        $else()
        $endif()
    $else()
    $endif()
    $return("a_bInitSystem")
!endprocedure


'#==============================================================================================
'# file : C:\workspace\c2puml\demo\example\system\core\user\s_init.c
'#==============================================================================================
$start_component("system.core.user")
$start_module("s_init.c")

'#----------------------------------------------------
'# func :  ## ATOM ## g_atomRegisterWcex ## ( const HINSTANCE a_hApp )
'#----------------------------------------------------
$start_func("g_atomRegisterWcex", "extern")
!procedure $g_atomRegisterWcex()
    $call("sizeof", "WNDCLASSEX")
    $step(" a_wcex.style = CS_HREDRAW | CS_VREDRAW;")
    $step(" a_wcex.lpfnWndProc = (WNDPROC)&g_lrWndProc;")
    $step(" a_wcex.cbClsExtra = 0;")
    $step(" a_wcex.cbWndExtra = 0;")
    $step(" a_wcex.hInstance = a_hApp;")
    $call("LoadImage", "NULL, IDI_APPLICATION, IMAGE_ICON, 0, 0, LR_SHARED")
    $call("LoadCursor", "NULL, IDC_ARROW")
    $step(" a_wcex.hbrBackground = (HBRUSH)(COLOR_WINDOW+1);")
    $step(" a_wcex.lpszMenuName = NULL;")
    $step(" a_wcex.lpszClassName = l_szAppName;")
    $call("LoadImage", "NULL, IDI_APPLICATION, IMAGE_ICON, 0, 0, LR_SHARED")
    $call("RegisterClassEx", " &a_wcex ")
    $return("a_atomResult")
!endprocedure

'#----------------------------------------------------
'# func :  ## HWND ## g_hwndCreateWindow ## ( const HINSTANCE a_hApp )
'#----------------------------------------------------
$start_func("g_hwndCreateWindow", "extern")
!procedure $g_hwndCreateWindow()
    $call("CreateWindowEx", " WS_EX_ACCEPTFILES, l_szAppName, l_szAppName, WS_OVERLAPPEDWINDOW & ~WS_MINIMIZEBOX, CW_USEDEFAULT, CW_USEDEFAULT, 300, 200, NULL, NULL, a_hApp, NULL ")
    $return("a_hWnd")
!endprocedure


'#==============================================================================================
'# file : C:\workspace\c2puml\demo\example\system\core\user\s_proc.c
'#==============================================================================================
$start_component("system.core.user")
$start_module("s_proc.c")

'#----------------------------------------------------
'# func :  ## LRESULT CALLBACK ## g_lrWndProc ## ( const HWND a_hwnd, const UINT a_msg, const WPARAM a_wparam, const LPARAM a_lparam )
'#----------------------------------------------------
$start_func("g_lrWndProc", "extern")
!procedure $g_lrWndProc()
    $return("g_lrExeHook( &g_lrWndProc, a_hwnd, a_msg, a_wparam, a_lparam )")
!endprocedure

'#----------------------------------------------------
'# func :  ## LRESULT CALLBACK ## g_lrWndProcEctl ## ( const HWND a_hwnd, const UINT a_msg, const WPARAM a_wparam, const LPARAM a_lparam )
'#----------------------------------------------------
$start_func("g_lrWndProcEctl", "extern")
!procedure $g_lrWndProcEctl()
    $return("g_lrExeHook( &g_lrWndProcEctl, a_hwnd, a_msg, a_wparam, a_lparam )")
!endprocedure


'#==============================================================================================
'# file : C:\workspace\c2puml\demo\example\system\core\user\s_sys_info.c
'#==============================================================================================
$start_component("system.core.user")
$start_module("s_sys_info.c")

'#----------------------------------------------------
'# func :  ## void ## l_voSetCmdLine ## ( const LPSTR a_szCmdLine )
'#----------------------------------------------------
$start_func("l_voSetCmdLine", "extern")
!procedure $l_voSetCmdLine()
    $step(" l_szCmdLine = a_szCmdLine;")
!endprocedure

'#----------------------------------------------------
'# func :  ## void ## l_voSetHndApp ## ( const HINSTANCE a_hApp )
'#----------------------------------------------------
$start_func("l_voSetHndApp", "extern")
!procedure $l_voSetHndApp()
    $step(" l_hApp = a_hApp;")
!endprocedure

'#----------------------------------------------------
'# func :  ## LPSTR ## l_lpstrGetCmdLine ## ( void )
'#----------------------------------------------------
$start_func("l_lpstrGetCmdLine", "extern")
!procedure $l_lpstrGetCmdLine()
    $return("l_szCmdLine")
!endprocedure

'#----------------------------------------------------
'# func :  ## HINSTANCE ## l_hInstGetHndApp ## ( void )
'#----------------------------------------------------
$start_func("l_hInstGetHndApp", "extern")
!procedure $l_hInstGetHndApp()
    $return("l_hApp")
!endprocedure


'#==============================================================================================
'# file : C:\workspace\c2puml\demo\example\system\hook\lib\s_hook_exe.c
'#==============================================================================================
$start_component("system.hook.lib")
$start_module("s_hook_exe.c")

'#----------------------------------------------------
'# func :  ## LRESULT ## g_lrExeHook ## ( const WNDPROC a_wndproc, const HWND a_hwnd, const UINT a_msg, const WPARAM a_wparam, const LPARAM a_lparam )
'#----------------------------------------------------
$start_func("g_lrExeHook", "extern")
!procedure $g_lrExeHook()
    $step(" a_prmHook.m_hwnd = a_hwnd;")
    $step(" a_prmHook.m_msg = a_msg;")
    $step(" a_prmHook.m_wparam = a_wparam;")
    $step(" a_prmHook.m_lparam = a_lparam;")
    $call("g_hooktblGet", " a_wndproc ")
    $call("l_hookGet", " &a_prmHook, a_hookInfoTbl ")
    $call("a_fptrHook", " &a_prmHook ")
    $return("a_lrResult")
!endprocedure

'#----------------------------------------------------
'# func : static ## lrCallHook ## l_hookGet ## ( xn_hook_prm_ptr a_prmHook, const xn_hook_info_tbl * a_hookInfoTbl )
'#----------------------------------------------------
$start_func("l_hookGet", "static")
!procedure $s_hook_exe_c_____l_hookGet()
    $step(" a_fptrHook = NULL;")
    $for("a_cnt = 0; a_cnt < a_hookInfoTbl->m_len; a_cnt++ ")
        $if("a_hookInfoTbl->m_tbl[ a_cnt ].m_wndMsg == a_prmHook->m_msg ")
            $step(" a_fptrHook = a_hookInfoTbl->m_tbl[ a_cnt ].m_hook;")
        $else()
        $endif()
    $endfor()
    $if("a_fptrHook == NULL ")
        $if("a_hookInfoTbl->m_hook == NULL ")
            $step(" a_fptrHook = &g_lrHookDefWindowProc;")
        $else()
            $step(" a_fptrHook = a_hookInfoTbl->m_hook;")
        $endif()
    $else()
    $endif()
    $return("a_fptrHook")
!endprocedure


'#==============================================================================================
'# file : C:\workspace\c2puml\demo\example\system\hook\user\s_user_hook_cmn.c
'#==============================================================================================
$start_component("system.hook.user")
$start_module("s_user_hook_cmn.c")

'#----------------------------------------------------
'# func :  ## BOOL ## g_boolHookInitApp ## ( void )
'#----------------------------------------------------
$start_func("g_boolHookInitApp", "extern")
!procedure $g_boolHookInitApp()
    $return("TRUE")
!endprocedure

'#----------------------------------------------------
'# func :  ## void ## g_voHookTermApp ## ( void )
'#----------------------------------------------------
$start_func("g_voHookTermApp", "extern")
!procedure $g_voHookTermApp()
!endprocedure

'#----------------------------------------------------
'# func :  ## LRESULT ## g_lrHookDefWindowProc ## ( xn_hook_prm_ptr a_prmHook )
'#----------------------------------------------------
$start_func("g_lrHookDefWindowProc", "extern")
!procedure $g_lrHookDefWindowProc()
    $call("DefWindowProc", " a_prmHook->m_hwnd, a_prmHook->m_msg, a_prmHook->m_wparam, a_prmHook->m_lparam ")
    $return("a_lrResult")
!endprocedure

'#----------------------------------------------------
'# func :  ## LRESULT ## g_lrHookParentWindowProc ## ( xn_hook_prm_ptr a_prmHook )
'#----------------------------------------------------
$start_func("g_lrHookParentWindowProc", "extern")
!procedure $g_lrHookParentWindowProc()
    $call("GetClassLongPtr", " a_prmHook->m_hwnd, GCLP_WNDPROC ")
    $if("a_wproc == 0 ")
        $call("g_lrHookDefWindowProc", " a_prmHook ")
    $else()
        $call("CallWindowProc", " a_wproc, a_prmHook->m_hwnd, a_prmHook->m_msg, a_prmHook->m_wparam, a_prmHook->m_lparam ")
    $endif()
    $return("a_lrResult")
!endprocedure


'#==============================================================================================
'# file : C:\workspace\c2puml\demo\example\system\hook\user\s_user_hook_main.c
'#==============================================================================================
$start_component("system.hook.user")
$start_module("s_user_hook_main.c")

'#----------------------------------------------------
'# func :  ## LRESULT ## g_lrHookMainWM_DESTROY ## ( xn_hook_prm_ptr a_prmHook )
'#----------------------------------------------------
$start_func("g_lrHookMainWM_DESTROY", "extern")
!procedure $g_lrHookMainWM_DESTROY()
    $call("PostQuitMessage", " 0 ")
    $call("g_lrHookDefWindowProc", " a_prmHook ")
    $return("a_lrResult")
!endprocedure

'#----------------------------------------------------
'# func :  ## LRESULT ## g_lrHookMainWM_CLOSE ## ( xn_hook_prm_ptr a_prmHook )
'#----------------------------------------------------
$start_func("g_lrHookMainWM_CLOSE", "extern")
!procedure $g_lrHookMainWM_CLOSE()
    $call("g_lrHookDefWindowProc", " a_prmHook ")
    $return("a_lrResult")
!endprocedure


'#==============================================================================================
'# file : C:\workspace\c2puml\demo\example\system\hook\user\s_user_hook_tbl.c
'#==============================================================================================
$start_component("system.hook.user")
$start_module("s_user_hook_tbl.c")

'#----------------------------------------------------
'# func :  ## const xn_hook_info_tbl * ## g_hooktblGet ## ( const WNDPROC a_wndproc )
'#----------------------------------------------------
$start_func("g_hooktblGet", "extern")
!procedure $g_hooktblGet()
    $step(" a_idx = L_DAT_ERR_TABLE_SEARCH;")
    $for("a_cnt = L_IDX_MSG_HOOK_NORMAL_START; a_cnt < L_IDX_MSG_HOOK_MAX; a_cnt++ ")
        $if("l_hookinfoTbls[a_cnt].m_wndproc == a_wndproc ")
            $step(" a_idx = a_cnt;")
        $else()
        $endif()
    $endfor()
    $if("a_idx == L_DAT_ERR_TABLE_SEARCH ")
        $step(" a_idx = L_IDX_MSG_HOOK_FAILSAFE;")
    $else()
    $endif()
    $return("&l_hookinfoTbls[ a_idx ]")
!endprocedure


' $display_outline()
' $call("EntryPoint")
@enduml

