@startuml




' 配列にデータを追加する(配列が存在しない場合、同時に作成する)
!procedure $push_to( $array_name, $value )
    !if %variable_exists( "__array_" + $array_name )
        !$pos = %get_variable_value( "__array_" + $array_name )
        !$pos = $pos + 1
        %set_variable_value( "__array_" + $array_name, $pos )
        %set_variable_value( "__array_" + $array_name + "[" + $pos + "]", $value )
    !else
        !$pos = 0
        %set_variable_value( "__array_" + $array_name, $pos )
        %set_variable_value( "__array_" + $array_name + "[" + $pos + "]", $value )
    !endif
!endprocedure

' 配列全要素に対してcallbackを呼ぶ
!procedure $iterate_array( $array_name, $callback )
    !$pos = 0
    !while %variable_exists( "__array_" + $array_name + "[" + $pos + "]" )
        %invoke_procedure($callback, %get_variable_value( "__array_" + $array_name + "[" + $pos + "]" ) )
        !$pos = $pos + 1
    !endwhile
!endprocedure

' 配列が特定のデータを有するならtrueを返す
!function $array_has_specific_data( $array_name, $specific_data )
    !$pos = 0
    !while %variable_exists( "__array_" + $array_name + "[" + $pos + "]" )
        !if $specific_data == %get_variable_value( "__array_" + $array_name + "[" + $pos + "]" )
            !return %true()
        !endif
        !$pos = $pos + 1
    !endwhile
    !return %false()
!endfunction








@enduml
