@startuml

' スタックポインタ
!$stack_p_ = 0

' スタックサイズ
!$stack_size_ = 300

' スタックポインタを進める
!procedure $inc_stack_()
    !if $stack_size_ < $stack_p_
        !assert %false() : "stack positive overflow"
    !endif
    !$stack_p_ = $stack_p_ + 1
!endprocedure

' スタックポインタを戻す
!procedure $dec_stack_()
    !if $stack_p_ < 0
        !assert %false() : "stack negative overflow"
    !endif
    !$stack_p_ = $stack_p_ - 1
!endprocedure

' 現在のスタック位置に値をセットする
!procedure $set_value_in_current_stack( $name, $value )
    %set_variable_value( $get_variable_name_for_stack( $name ) + $stack_p_ , $value )
!endprocedure

' 現在のスタック位置から値をゲットする
!function $get_value_in_current_stack( $name )
    !return %get_variable_value( $get_variable_name_for_stack( $name ) + $stack_p_ )
!endfunction

' 前回のスタック位置から値をゲットする
!function $get_value_in_prev_stack( $name )
    !return %get_variable_value( $get_variable_name_for_stack( $name ) + ( $stack_p_ - 1 ) )
!endfunction

' スタックの変数名
!function $get_variable_name_for_stack( $name )
    !return "__stack_" + $name + "_position_"
!endfunction

@enduml
